"""
Script that extracts and saves in separated files (.h5qpsike) each recording found in a MCS HDF5 file (.h5) 
using the H5Py Python library.

MCS (Multi Channel Systems) HDF5 files are generated by the Multi Channel DataManager from .mcd or .msrd files. The
specification of these files can be found in their [their website](https://www.multichannelsystems.com/sites/multichannelsystems.com/files/documents/manuals/HDF5%20MCS%20Raw%20Data%20Definition.pdf).
The new files contain one group per each stream found in the recording, tagging them as ElectrodeStream or DigitalStream
as it corresponds. Each group have the following fields:

- `NumberChannels` : number of channels.
- `NumberSamples` : number of samples.
- `SamplingRate` : sampling rate (Hz).
- `Duration` : duration (ms).
- `Exponent` : exponent n (i.e. 10^n) in which channels values magnitude is measured (e.g. k, m, u, ...).
- `ADZero` : ADC-Step that represent the 0-point of the measuring range of the ADC.
- `ConversionFactor` : conversion factor for the mapping ADC-Step -> measured value.
- `ChannelsIDs` : vector with the IDs of each channel.
- `ChannelData` : matrix with the data recorded from each channel (numberChannels x numberSamples).


### Arguments
- `filename::String` : full path of the input MCS HDF5 (.h5) file.

### Examples
```jldoctest
julia src/private/src/private/demultiplexH5Py.jl "data/INPUT_FILES/trace1.h5"
```

### Authors
- Michele Giugliano - mgiugliano@gmail.com
- Rodrigo Amaducci - amaducci.rodrigo@gmail.com
"""

using PyCall

h5py = pyimport("h5py")

filename = ARGS[1];
sessionName = replace(filename, ".h5" => "");

py"""
import h5py

#InfoChannel indexes
CHANNELID = 0;
ROWINDEX = 1;
GROUPID = 2;
ELECTRODEGROUP = 3;
LABEL = 4;
RAWDATATYPE = 5;
UNIT = 6;
EXPONENT = 7;
ADZERO = 8;
TICK = 9;
CONVERSIONFACTOR = 10;

def multiplex(filename, sessionName):
	with h5py.File(filename, "r") as fid:
		print("Loaded file ", filename)

		data = fid["Data"]
		numberRecordings = len(data)
		print("Number of recordings: ", numberRecordings)

		for i in range(numberRecordings):
			rName = "Recording_" + str(i)
			recording = data[rName]

			analogStreams = recording["AnalogStream"]
			numberAnalogStreams = len(analogStreams)
			
			print("\nAnalyzing " + rName + " with " + str(numberAnalogStreams) + " stream(s):")

			with h5py.File(sessionName + "_rec" + str(i) + ".h5qspike", "w") as outFile:

				for j in range(numberAnalogStreams):
					sName = "Stream_" + str(j)
					stream = analogStreams[sName]
					type = stream.attrs.get("DataSubType")
				
					channelData = stream["ChannelData"]
					infoChannel = stream["InfoChannel"]

					groupType = "UnknownStream"
					if type == b'Digital':
						groupType = "DigitalStream_" + str(j)
					elif type == b'Electrode':
						groupType = "ElectrodeStream_" + str(j)
					elif type == b'Auxiliary':
						groupType = "AuxiliaryStream_" + str(j)

					g1 = outFile.create_group(groupType)

					dataShape = channelData.shape
					numberChannels = dataShape[0]
					numberSamples = dataShape[1]
					samplingRate = int(1000000 / infoChannel[0][TICK])
					duration = int((numberSamples / samplingRate) * 1000)
					exponent = infoChannel[0][EXPONENT]
					ADZero = infoChannel[0][ADZERO]
					conversionFactor = infoChannel[0][CONVERSIONFACTOR]

					g1.create_dataset("NumberChannels", data=numberChannels)
					g1.create_dataset("NumberSamples", data=numberSamples)
					g1.create_dataset("SamplingRate", data=samplingRate)
					g1.create_dataset("Duration", data=duration)
					g1.create_dataset("Exponent", data=exponent)
					g1.create_dataset("ADZero", data=ADZero)
					g1.create_dataset("ConversionFactor", data=conversionFactor)

					print("\t" + sName + " has " + str(numberChannels) + " channel(s)")

					channelsIds = [];
					for k in range(numberChannels):
						channelsIds.append(infoChannel[k][LABEL])

					g1.create_dataset("ChannelsIDs", data=channelsIds, compression="gzip", compression_opts=2)
					g1.create_dataset("ChannelData", data=channelData, compression="gzip", compression_opts=2)
"""

py"multiplex"(filename, sessionName)