"""
	generate_latex_file(info::INFO, bursts::BURSTS)

Generate a latex file for automated report generation at the end of the preprocessing and analysis. 
The generated latex file includes information from activity information file and the figures.

### Arguments
- `info::INFO` : structure that stores the general information of the analysis.
- `bursts::BURSTS` : structure that stores the results of the burst analysis.

### Authors
- Michele Giugliano - mgiugliano@gmail.com
- Rodrigo Amaducci - amaducci.rodrigo@gmail.com
"""

function generate_latex_file(info::INFO, bursts::BURSTS)
	# Creates (or overwrites) and open the .tex
	filename = string(info.outpath, info.expName, ".tex");
	fid = open(filename, "w");
	println("Writing analysis report into file ", filename);

	# Generate header for the file
	write(fid, "\\documentclass[11pt,twoside,a4paper]{article}\n\n");
	write(fid, "\\usepackage{pslatex,palatino,avant,color}\n");
	write(fid, "\\usepackage[margin=2cm]{geometry}\n");
	write(fid, "\\usepackage{fancyhdr}\n");
	write(fid, "\\usepackage[pdftex]{graphicx}\n");
	write(fid, "\\usepackage{datetime}\n\n");
	write(fid, "\\pagestyle{fancy}\n\n");

	write(fid, "\\begin{document}\n\n");
	write(fid, "\\title{Summary of analysis for data file: $(info.expName).mcd}\n");
	write(fid, "\\author{This report has been automatically generated by a web-based analysis tool kit \\\\ Generated on \\today\\ at \\currenttime}\n\n");
	write(fid, "\\maketitle\n\n");


	# Write the activity information
	write(fid, "\\section{Summary of the Activity}\n\n");
	write(fid, "Activity Information Extracted from the Recording Data\\\\\n");
	write(fid, "------------------------------------------------------\\\\\n");
	write(fid, "\\textbf{Recording Duration                  :} $(info.T) ms\\\\\n");
	write(fid, "\\textbf{Number of Samples                   :} $(info.Ns)\\\\\n");
	write(fid, "\\textbf{Sampling Rate                       :} $(info.sr) Hz\\\\\n");
	write(fid, "\\textbf{Number of Active Electrodes         :} $(info.nActiveElectrodes)\\\\\n");
	write(fid, "\\textbf{Number of Spikes                    :} $(bursts.Nspikes)\\\\\n");
	write(fid, "\\textbf{Number of Bursts                    :} $(bursts.Nburst)\\\\\n");
	write(fid, "\\textbf{Mean Burst Duration                 :} $(bursts.meanDUR) ms\\\\\n");
	write(fid, "\\textbf{Standard Deviation of Burst Duration:} $(bursts.stdDUR) ms\\\\\n");
	write(fid, "\\textbf{Mean Inter-Burst-Interval (IBI)     :} $(bursts.meanIBI) ms\\\\\n");
	write(fid, "\\textbf{Standard Deviation of IBI           :} $(bursts.stdIBI) ms\\\\\n");
	write(fid, "\\textbf{Burst Detection Threshold           :} $(bursts.TH)\\\\\n");


	# !! write the log file (which log file??)

	# Add the code for the figures
	figuresFiles = filter!(s->occursin(".pdf", s) ,readdir(info.outpath));
	numberFigures = length(figuresFiles);

	println("Number of figures found: ", numberFigures);

	figuresCaptions = ["Sample activity (first 300 seconds) from the data file.",
						"Negative spikes detected at distinct MEA microelectrodes.", 
						"Positive spikes detected at distinct MEA microelectrodes.",
						"Histogram of the electrodes number where multi-unit activity was detected above 0.02 Hz.",
						"Inter spike interval (ISI) distribution of the detected events.",
						"Burst trigerred instantaneous firing probability across electrodes.",
						"Multi-unit time raster and event time diagram, centered around the most intense burst recorded.",
						"Detail of multi-unit time raster and event time diagram, centered around the most intense burst recorded.",
						"Corresponding raw voltage traces across MEA electrodes to the burst of Figure \\ref{largest_burst}.", 
						"Detail of corresponding raw voltage traces across MEA electrodes to the burst of Figure \\ref{largest_burst_zoom}."];
	includeFigFiles = ["sample_raster_psth.pdf", 
						"negative_waves.pdf",
						"positive_waves.pdf",
						"active_electrodes.pdf",
						"frequency_distribution.pdf",
						"vanpelt_plot_complete.pdf",
						"largest_burst.pdf",
						"largest_burst_zoom.pdf",
						"largest_burst_raw.pdf",
						"largest_burst_rawzoom.pdf"];

	write(fid, "\n\n\\section{Results Summary}\n\n");

	for i in 1:10
		if includeFigFiles[i] in figuresFiles
			write(fid, "\\begin{figure*}[tbh!]\n");
			write(fid, "\\centering\n");
			write(fid, "\\includegraphics[width=6in]{$(includeFigFiles[i])}\n");
			write(fid, "\\caption{$(figuresCaptions[i])}\n");
			write(fid, "\\label{$(includeFigFiles[i][1:end-4])}\n");
			write(fid, "\\end{figure*}\n\n");
		end
	end

	write(fid, "\n\\end{document}\n");

	close(fid);


end 
